# Generated by Django 5.2 on 2025-04-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nueva_app', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='post_tags', to='nueva_app.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='tag_posts', to='nueva_app.post'),
        ),
    ]
